#!/usr/bin/env bash
set -euo pipefail

SOURCE_URL="https://gin.g-node.org/BrainGlobe/atlases/raw/master/last_versions.conf"
OUTPUT="brainglobe_atlasapi/atlas_name.py"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-url)
      SOURCE_URL="$2"
      shift 2
      ;;
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

conf_text=$(curl -fsSL "$SOURCE_URL")

mapfile -t atlas_names < <(
  printf "%s" "$conf_text" \
    | awk 'BEGIN{in_atlases=0} /^\[atlases\]/{in_atlases=1; next} /^\[/{in_atlases=0} in_atlases && $0 ~ /^[[:space:]]*[^#;[:space:]][^=]*=/{print $1}' \
    | sed 's/[[:space:]]//g' \
    | sort
)

{
  printf '%s\n' '"""Defines all available valid atlas names for autocomplete.'
  printf '%s\n' ''
  printf '%s\n' 'This file is auto-generated by scripts/generate_atlas_name.sh.'
  printf '%s\n' 'Do not edit by hand.'
  printf '%s\n' '"""'
  printf '%s\n' ''
  printf '%s\n' 'from typing import Literal, TypeAlias'
  printf '%s\n' ''
  printf '%s\n' 'AtlasName: TypeAlias = Literal['
  for name in "${atlas_names[@]}"; do
    printf '    "%s",\n' "$name"
  done
  printf '%s\n' ']'
} > "$OUTPUT"
